# Generated by Django 2.2.6 on 2021-04-07 02:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0007_auto_20210404_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default='', help_text='Задача', max_length=50, verbose_name='Задача'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='group',
            field=models.ForeignKey(blank=True, help_text='Выберите тип задачи, если требуется', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deals', to='deals.Group', verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Когда следует сделать'),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(help_text='Напишите подробно, что нужно сделать', max_length=500, verbose_name='Описание задачи'),
        ),
    ]
