# Generated by Django 2.2.6 on 2021-04-13 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0008_auto_20210411_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='deals/static/', verbose_name='Фотография'),
        ),
    ]
