# Generated by Django 2.2.6 on 2021-04-07 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0008_auto_20210407_0536'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='making_time',
            field=models.CharField(choices=[('1m', '1 минута'), ('5m', '5 минут'), ('15', '15 минут'), ('1h', '1 час'), ('3h', '1 часа'), ('12', '1/2 дня'), ('1d', '1 день'), ('3d', 'Несколько дней'), ('88', '')], default='15', help_text='Сколько времени потребуется на выполнение этой задачи', max_length=2, verbose_name='Время на выполнение'),
        ),
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Когда следует начать делать'),
        ),
    ]
