# Generated by Django 2.2.6 on 2021-04-19 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0009_auto_20210407_0602'),
        ('deals', '0014_auto_20210416_1221'),
    ]

    operations = [
    ]
