# Generated by Django 2.2.6 on 2021-04-19 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0016_auto_20210419_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='done',
            field=models.BooleanField(default=False, help_text='Это задание уже выполнено?', verbose_name='Прогресс'),
        ),
    ]
