# Generated by Django 2.2.6 on 2021-04-22 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0017_deal_done'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deal',
            name='done',
        ),
        migrations.RemoveField(
            model_name='subdeal',
            name='done',
        ),
        migrations.AddField(
            model_name='deal',
            name='status',
            field=models.CharField(default="Isn't done", help_text='Это задание уже выполнено?', max_length=20, verbose_name='Прогресс'),
        ),
        migrations.AddField(
            model_name='subdeal',
            name='status',
            field=models.CharField(default="Isn't done", help_text='Это задание уже выполнено?', max_length=20, verbose_name='Прогресс'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='expected_date',
            field=models.DateTimeField(auto_now_add=True, help_text='Когда следует сделать', verbose_name='Запланировано'),
        ),
        migrations.AlterField(
            model_name='subdeal',
            name='quantity',
            field=models.FloatField(blank=True, default=0, help_text='Какое количество требуется', max_length=10, null=True, verbose_name='Количество'),
        ),
    ]
